### PR TITLE
fix: remove NoT

### LINKED ISSUE #15: Remove Termennetwerk from demo page
The entry for the netwerk-of-terms on the demo page should be removed as we decided it has no longer the demo status and the front-end is available now through a dedicated url.

### PR DESCRIPTION
**Pull request by sdevalk**
Fix #15.

### CODE REVIEW

**Comment by ddeboer** [comment]
If you change this PR’s description to `Fix #15` merging it will auto-close that issue. Long live automation. 👨‍🔧

**Comment by ddeboer** [comment]
It’s not too late, you can still edit the description, before I merge. 😁

**Comment by sdevalk** [comment]
> It’s not too late, you can still edit the description, before I merge. 😁

Done! 😅

**Comment by ddeboer** [comment]
Hehe, not the title but the description. Anyway, changed it.

**Pull request merged**
